language: ruby
rvm:
 - 2.2

bundler_args: --without development
cache: bundler

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

